//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "listening_state")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub channel_id: i32,
    pub channel_item_enclosure: String,
    #[sea_orm(column_type = "Double")]
    pub time: f64,
    pub finished: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel::Entity",
        from = "Column::ChannelId",
        to = "super::channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channel,
    #[sea_orm(
        belongs_to = "super::channel_item::Entity",
        from = "Column::ChannelItemEnclosure",
        to = "super::channel_item::Column::Enclosure",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelItem,
}

impl Related<super::channel_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelItem.def()
    }
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        super::channel_item::Relation::Channel.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::channel_item::Relation::ListeningState.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
